image:
  repository: jyupk/my-msa-product-service
  tag: 1eea0ea7b8744bca6836528ca5bab3d0e9893dab
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9090

serviceMonitor:
  enabled: true

ingress:
  enabled: false

appConfig:
  spring:
    application:
      name: product-service
    datasource:
      url: jdbc:postgresql://postgresql.postgresql.svc.cluster.local:5432/product_db
      username: product-service
      password: product-service
      driver-class-name: org.postgresql.Driver
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: create
      generate-ddl: true
      show-sql: true
  server:
    port: 8080
  grpc:
    server:
      port: 9090
  management:
    endpoints:
      web:
        base-path: /
        path-mapping:
          health: healthz
        exposure:
          include: health,prometheus
    endpoint:
      health:
        show-details: always
      prometheus:
        enabled: true
