image:
  repository: jyupk/my-msa-product-service
  tag: 852c5e5c6655f71af6bbfc55f3a061b502be1d15
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9090

serviceMonitor:
  enabled: true

ingress:
  enabled: false

appConfig:
  spring:
    application:
      name: product-service
    datasource:
      url: jdbc:postgresql://product-db-rw.postgresql.svc.cluster.local:5432/product_db
      username: product-service
      password: product-service
      driver-class-name: org.postgresql.Driver
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: update
      generate-ddl: true
      show-sql: true
  server:
    port: 8080
  grpc:
    server:
      port: 9090
  management:
    endpoints:
      web:
        base-path: /
        path-mapping:
          health: healthz
        exposure:
          include: health,prometheus
    endpoint:
      health:
        show-details: always
      prometheus:
        enabled: true
    tracing:
      sampling:
        probability: 1.0
    otlp:
      tracing:
        endpoint: http://tempo.monitoring.svc.cluster.local:4318/v1/traces
