image:
  repository: jyupk/my-msa-order-service
  tag: 007173fa7c1ae1333fcce4df395e3b6b6cc2f42d
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9090

serviceMonitor:
  enabled: true

ingress:
  enabled: false

appConfig:
  spring:
    application:
      name: order-service
    datasource:
      url: jdbc:postgresql://order-db-rw.postgresql.svc.cluster.local:5432/order_db
      username: order-service
      password: order-service
      driver-class-name: org.postgresql.Driver
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: update
      generate-ddl: true
      show-sql: true
    kafka:
      bootstrap-servers: kafka.kafka.svc.cluster.local:9092
      consumer:
        group-id: order-service-group
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      topic:
        inventory-reserved-result: inventory-reserved-result-topic
        inventory-reserve-request: inventory-reserve-request-topic
  server:
    port: 8080
  grpc:
    server:
      port: 9090
  management:
    endpoints:
      web:
        base-path: /
        path-mapping:
          health: healthz
        exposure:
          include: health,prometheus
    endpoint:
      health:
        show-details: always
      prometheus:
        enabled: true
    tracing:
      sampling:
        probability: 1.0
    otlp:
      tracing:
        endpoint: http://tempo.monitoring.svc.cluster.local:4318/v1/traces
