image:
  repository: kanei0415/ktcloud-msa-order-service
  tag: latest
  pullPolicy: IfNotPresent

serviceName: order-service
replicaCount: 2

env:
  SPRING_PROFILES_ACTIVE: "release"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi