image:
  repository: jyupk/my-msa-user-api-gateway
  tag: 9e0525ba8ce87ddfe0eeea1b8b53dc220fbfd408
  pullPolicy: IfNotPresent

serviceMonitor:
  enabled: false

addons:

service:
  type: ClusterIP 
  port: 8080

ingress:
  enabled: false
      

appConfig:
  spring:
    application:
      name: user-api-gateway
    autoconfigure:
      exclude:
        - net.devh.boot.grpc.client.autoconfigure.GrpcClientMicrometerTraceAutoConfiguration
        - net.devh.boot.grpc.client.autoconfigure.GrpcClientMetricAutoConfiguration
    cloud:
      gateway:
        routes:
          - id: auth-service
            uri: http://auth-service.default.svc.cluster.local:8080
            predicates:
              - Path=/api/auth/**
          - id: user-service
            uri: http://user-service.default.svc.cluster.local:8080
            predicates:
              - Path=/api/v1/users/**
          - id: order-service
            uri: http://order-service.default.svc.cluster.local:8080
            predicates:
              - Path=/api/orders/**
          - id: product-service
            uri: http://product-service.default.svc.cluster.local:8080
            predicates:
              - Path=/api/products/**
          - id: inventory-service
            uri: http://inventory-service.default.svc.cluster.local:8080
            predicates:
              - Path=/api/inventories/**
  grpc:
    client:
      product-service:
        address: 'dns:///product-service.default.svc.cluster.local:9090'
        negotiation-type: plaintext
      order-service:
        address: 'dns:///order-service.default.svc.cluster.local:9090'
        negotiation-type: plaintext
      inventory-service:
        address: 'dns:///inventory-service.default.svc.cluster.local:9090'
        negotiation-type: plaintext
  jwt:
    secret: 'v7S6A9yB2E5H8KcNfUjXnZr4u7x!A%D*G-'
  server:
    port: 8080
  management:
    endpoints:
      web:
        base-path: /
        path-mapping:
          health: healthz
    endpoint:
      health:
        show-details: always
    tracing:
      sampling:
        probability: 1.0
    otlp:
      tracing:
        endpoint: http://tempo.monitoring.svc.cluster.local:4318/v1/traces
  springdoc:
    swagger-ui:
      path: /swagger-ui.html
      groups-order: DESC
      operations-sorter: alpha
    api-docs:
      path: /v3/api-docs


