image:
  repository: kanei0415/ktcloud-msa-user-api-gateway
  tag: e4132704ab2445fafdbc66aacd8cf00a0b97413f
  pullPolicy: IfNotPresent

addons:
  

service:
  type: LoadBalancer

appConfig:
  spring:
    application:
      name: user-api-gateway
  grpc:
    client:
      product-service:
        address: 'static://product-service-release.svc.ktcloud-market-msa-release:9090'
        negotiation-type: plaintext
      order-service:
        address: 'static://order-service-release.svc.ktcloud-market-msa-release:9090'
        negotiation-type: plaintext
      inventory-service:
        address: 'static://inventory-service-release.svc.ktcloud-market-msa-release:9090'
        negotiation-type: plaintext
  jwt:
    secret: '${JWT_SECRET_ENV}'
  server:
    port: 8080
  management:
    endpoints:
      web:
        base-path: /
        path-mapping:
          health: healthz
    endpoint:
      health:
        show-details: always
  springdoc:
    swagger-ui:
      path: /swagger-ui.html
      groups-order: DESC
      operations-sorter: alpha
    api-docs:
      path: /v3/api-docs